### ISSUE TITLE
Comparison with gstreamer plugin?

### ISSUE THREAD

**Issue by daveisfera** [awslabs/aws-streamer#8]
How does this relate to/compare with the [gstreamer plugin for uploading video to KVS](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp)?

**Comment by bpawlik** [comment]
`awstreamer` is a framework that allows you to create entire video pipeline end-to-end, whereas `kvssink` plug-in is just one part of it.

As a matter of fact, there is a build flag that allows you to compile KVS SDK and `kvssink` plug-in from the repository that you pointed to: https://github.com/awslabs/aws-streamer/blob/09525140b4d080e647be2a1a830233318634db8d/awstreamer/CMakeLists.txt#L75-L80

**Comment by daveisfera** [comment]
So is this an alternative that should be considered in place of the current `gstreamer` setup when mapping an RTSP stream from an IP Camera to KVS? Just trying to understand if this is something we should look into using or if we should stick with `gstreamer`.

**Comment by bpawlik** [comment]
It is not alternative to GStreamer, more of a wrapper on top of GStreamer and AWS services. It builds GStreamer pipeline(s) underneath and connects the dots for user, meant to streamline entire process of building and managing video pipelines.

**Comment by bpawlik** [comment]
@daveisfera Is there anything else I could help regarding this issue?

**Comment by daveisfera** [comment]
No, I think I understand now.
