### ISSUE TITLE
Unnecessary LoadBalancer in Serverless Example?

### ISSUE THREAD

**Issue by leagerl1** [awslabs/aws-streamer#9]
We are playing with the serverless example in this repo and found that the ECS task enters a crash loop. This would appear to be because of a failing healthcheck from the load balancer to the target group. This appears to be because the image used in this example is not a web service at all and therefore does not have any healthcheck http endpoint. The application run by the task is a simple python script that runs an infinite loop to consume off of SQS. This has no healthcheck endpoint (or any endpoints at all) and therefore fails creating the crash loop. My question is why this example even includes a load balancer at all then? Couldn't this be removed entirely? And what is the best practice for creating an auto-scaling consumer that isn't an HTTP web service?

**Comment by bpawlik** [comment]
Hi,

Thanks for trying out aws-streamer!

LoadBalancer is kind of a residual of using EC2 in this example in the past, I believe it can be safely removed.

As for `best practice for creating an auto-scaling consumer `, do you mean consuming video stream? KVS (Kinesis Video Streams) offers scalable solutions there. If you relate to the use of API gateway, then that is scalable as well, as far as I know. I'm not really an expert on that end.

Thanks,
Bartek

**Comment by leagerl1** [comment]
Makes sense, we have removed the unnecessary LoadBalancer as suggested and seems to cause no deployment issues!
